const vscode=require('vscode');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs/promises');

exports.run=async function () {
  const root=process.env.LEAN_PROFILE_TEST_ROOT;
  const source=path.join(root,'test','fixtures','SourceProfileFixtures','Accuracy.lean');
  const extension=vscode.extensions.getExtension('local-lean-tools.lean-source-profiler');
  assert.ok(extension,'extension is installed in development host');
  const api=await extension.activate();
  await vscode.workspace.getConfiguration('editor').update('codeLens',true,vscode.ConfigurationTarget.Workspace);
  const document=await vscode.workspace.openTextDocument(source);
  await vscode.window.showTextDocument(document);
  const profile=await api.profileFile(document.uri);
  assert.ok(profile?.nodes.length>0,'Profile button produces recording and returns it');
  assert.ok(profile.profilePath.endsWith('.leanprofile.json'));
  assert.equal(JSON.parse(await fs.readFile(profile.profilePath,'utf8')).sourceFile,source);
  const getLenses=async()=> (await vscode.commands.executeCommand('vscode.executeCodeLensProvider',document.uri))?.filter(l=>l.command?.command==='leanSourceProfiler.inspectNode')??[];
  let lenses=await getLenses();
  assert.ok(lenses.length>=10,`source has >=10 timing lenses, got ${lenses.length}`);
  const expected=JSON.parse(await fs.readFile(path.join(root,'test','fixtures','expected-ranges.json'),'utf8'));
  // Exact tactic invocation locations include repeated and multiline syntax; UI shows a bar per start line.
  assert.ok(lenses.some(l=>l.range.start.line===7),'funext line has a clickable annotation');
  assert.ok(lenses.some(l=>l.range.start.line===8),'exact line has a separate annotation');
  const exact=profile.nodes.find(n=>n.category==='Source.tactic'&&n.label.endsWith('.exact')&&n.source?.start.line===8);
  assert.ok(exact);
  await vscode.commands.executeCommand('leanSourceProfiler.inspectNode',exact.id);
  const selectedEditor=vscode.window.visibleTextEditors.find(e=>e.document.uri.fsPath===source);
  assert.equal(selectedEditor.selection.start.line,8,'clicking timing selects correct tactic');
  const navNode=profile.nodes.find(n=>n.symbols?.some(s=>s.file?.endsWith('Imported.lean')&&s.range));
  assert.ok(navNode,'semantic imported definition links recorded');
  const symbolIndex=navNode.symbols.findIndex(s=>s.file?.endsWith('Imported.lean')&&s.range);
  await vscode.commands.executeCommand('leanSourceProfiler.openSymbol',navNode.id,symbolIndex);
  assert.ok(vscode.window.visibleTextEditors.some(e=>e.document.uri.fsPath.endsWith('Imported.lean')),'definition navigation opens other source');
  await vscode.window.showTextDocument(document,vscode.ViewColumn.One);
  const change=new vscode.WorkspaceEdit();change.insert(document.uri,new vscode.Position(0,0),'-- changed after capture\n');
  await vscode.workspace.applyEdit(change);
  assert.equal((await getLenses()).length,0,'stale buffer suppresses timing annotations');
  const restore=new vscode.WorkspaceEdit();restore.delete(document.uri,new vscode.Range(0,0,1,0));
  await vscode.workspace.applyEdit(restore);
  assert.ok((await getLenses()).length>=10,'exact restoration restores annotations');
  await vscode.commands.executeCommand('leanSourceProfiler.toggleOverlay');
  assert.equal((await getLenses()).length,0,'toggle hides annotations');
  await vscode.commands.executeCommand('leanSourceProfiler.toggleOverlay');
  assert.ok((await getLenses()).length>=10);
  await vscode.commands.executeCommand('leanSourceProfiler.clear');
  assert.equal((await getLenses()).length,0,'clear removes annotation provider output');
  await api.openProfile(profile.profilePath);
  assert.ok((await getLenses()).length>=10,'open saved recording restores overlays without re-elaboration');
  await fs.mkdir(path.join(root,'test','results'),{recursive:true});
  await fs.writeFile(path.join(root,'test','results','extension-host.json'),JSON.stringify({passed:true,vscode:vscode.version,profile:profile.profilePath,events:profile.nodes.length,checks:['capture command','source CodeLens','tactic selection','imported definition navigation','stale source suppression','restoration','toggle','clear','open saved recording']},null,2));
  console.log('Extension-host integration checks passed.');
};
